engines:
  duplication: { enabled: true }
  eslint:      { enabled: true }
  flake8:      { enabled: true }
  gofmt:       { enabled: true }
  rustclippy:  { enabled: true }
ratings:
  paths:
    - "**/*.ts"
    - "**/*.tsx"
    - "**/*.js"
    - "**/*.py"
    - "**/*.go"
    - "**/*.rs"
exclude_paths:
  - "node_modules/**"
  - "dist/**"
  - "build/**"
  - "**/*.min.js"
