# InstallSure BIM Services - Unified Architecture
# GitHub Copilot + Cursor Integration
# Last Updated: 2025-10-06

version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15-alpine
    container_name: installsure-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: installsure
      POSTGRES_USER: installsure
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-installsure123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U installsure"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - installsure_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: installsure-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - installsure_network

  # Ollama (Local LLM)
  ollama:
    image: ollama/ollama:latest
    container_name: installsure-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - installsure_network

  # Gateway Service (Node.js/Fastify)
  gateway:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    container_name: installsure-gateway
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
      - DATABASE_URL=postgresql://installsure:${POSTGRES_PASSWORD:-installsure123}@postgres:5432/installsure
      - REDIS_URL=redis://redis:6379
      - BIM_SERVICE_URL=http://bim:8002
      - UPLOAD_SERVICE_URL=http://upload:8001
      - OLLAMA_URL=http://ollama:11434
    volumes:
      - ./services/gateway:/app
      - /app/node_modules
      - uploads_data:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      bim:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - installsure_network

  # Upload Service
  upload:
    build:
      context: ./services/upload
      dockerfile: Dockerfile
    container_name: installsure-upload
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - BIM_SERVICE_URL=http://bim:8002
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - installsure_network

  # BIM Service (Python/FastAPI)
  bim:
    build:
      context: ./services/bim
      dockerfile: Dockerfile
    container_name: installsure-bim
    restart: unless-stopped
    ports:
      - "8002:8002"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://installsure:${POSTGRES_PASSWORD:-installsure123}@postgres:5432/installsure
      - REDIS_URL=redis://redis:6379
      - OLLAMA_URL=http://ollama:11434
    volumes:
      - ./services/bim:/app
      - uploads_data:/app/data/uploads
      - reports_data:/app/data/reports
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - installsure_network

  # Web Frontend
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: installsure-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE=http://localhost:8000
      - VITE_BIM_SERVICE_URL=http://localhost:8002
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    depends_on:
      - gateway
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - installsure_network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  ollama_data:
    driver: local
  uploads_data:
    driver: local
  reports_data:
    driver: local

networks:
  installsure_network:
    driver: bridge
    name: installsure_network