# Guardrails Configuration for NexusLocalAI

guardrails:
  enabled: true
  
  # Content filters
  content_filters:
    - name: prompt_injection
      enabled: true
      severity: high
      action: block
      
    - name: pii_detection
      enabled: true
      severity: medium
      action: redact
      
    - name: toxic_content
      enabled: true
      severity: high
      action: warn

  # Rate limiting
  rate_limits:
    requests_per_minute: 60
    requests_per_hour: 1000
    
  # Token limits
  token_limits:
    max_input_tokens: 4096
    max_output_tokens: 2048
    
  # Model routing rules
  routing:
    - pattern: "code|debug|implement"
      model: qwen2.5-coder:7b
      
    - pattern: "explain|analyze"
      model: deepseek-coder-v2:16b
      
    - pattern: ".*"
      model: qwen2.5:7b
      fallback: true
