version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    
  router:
    build:
      context: ./router
      dockerfile: Dockerfile
    ports:
      - "8099:8099"
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
      - QDRANT_HOST=http://qdrant:6333
    depends_on:
      - qdrant
    restart: unless-stopped
    
  avatar:
    build:
      context: ./avatar
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    restart: unless-stopped

volumes:
  qdrant_storage:
