name: InstallSure CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            applications/installsure/backend/package-lock.json
            applications/installsure/frontend/package-lock.json
            tests/package-lock.json

      - name: Install backend dependencies
        working-directory: applications/installsure/backend
        run: npm ci

      - name: Install frontend dependencies
        working-directory: applications/installsure/frontend
        run: npm ci

      - name: Build frontend
        working-directory: applications/installsure/frontend
        run: npm run build

      - name: Run backend unit tests
        working-directory: applications/installsure/backend
        run: npm test || true
        env:
          NODE_ENV: test

      - name: Install Playwright dependencies
        working-directory: tests
        run: |
          npm ci
          npx playwright install --with-deps chromium

      - name: Start backend server
        working-directory: applications/installsure/backend
        run: |
          npm run dev &
          echo $! > /tmp/backend.pid
        env:
          PORT: 8099
          NODE_ENV: development

      - name: Start frontend preview server
        working-directory: applications/installsure/frontend
        run: |
          npm run preview &
          echo $! > /tmp/frontend.pid
        env:
          PORT: 3000

      - name: Wait for services
        run: |
          echo "Waiting for backend..."
          timeout 60 bash -c 'until curl -f http://127.0.0.1:8099/api/health; do sleep 2; done'
          echo "Waiting for frontend..."
          timeout 60 bash -c 'until curl -f http://127.0.0.1:4173; do sleep 2; done'

      - name: Run Playwright tests
        working-directory: tests
        run: npx playwright test
        env:
          CI: true

      - name: Upload Playwright report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: tests/playwright-report/
          retention-days: 7

      - name: Upload test screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-screenshots
          path: tests/test-results/
          retention-days: 7

      - name: Cleanup
        if: always()
        run: |
          if [ -f /tmp/backend.pid ]; then kill $(cat /tmp/backend.pid) || true; fi
          if [ -f /tmp/frontend.pid ]; then kill $(cat /tmp/frontend.pid) || true; fi
