name: Quality (Super Linter)
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Super-Linter
        uses: super-linter/super-linter@v6
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_PYTHON: true
          VALIDATE_GO: true
          VALIDATE_RUST: true
          IGNORE_GENERATED_FILES: true
